import './sheet-node';
import { startCollection, flushSync } from './sheet';
import { runWithIsolatedSheet } from './sheet-context';

/**
 * Collect all CSS generated by executing one or more loader functions.
 *
 * This is a low-level primitive intended for build tools (Vite, Next.js, etc.)
 * to implement a zero-runtime extraction step. On Node, each call uses an
 * isolated sheet store so concurrent extractions do not share state.
 *
 * Example usage (Vite/Node):
 *
 * ```ts
 * import { collectStylesFromModules } from 'typestyles/build';
 *
 * const css = await collectStylesFromModules([
 *   () => import('./src/styles'),
 *   () => import('./src/tokens'),
 * ]);
 * ```
 */
export async function collectStylesFromModules(
  loaders: Array<() => unknown | Promise<unknown>>,
): Promise<string> {
  return runWithIsolatedSheet(async () => {
    const endCollection = startCollection();

    for (const load of loaders) {
      // Each loader can synchronously or asynchronously import modules that
      // register typestyles styles, tokens, keyframes, etc.
      // We await in case a loader returns a promise (e.g. dynamic import).
      // The return value itself is ignored; only the side effects matter.
      await load();
    }

    flushSync();
    return endCollection();
  });
}
