/**
 * Shared registry for detecting duplicate namespace registrations.
 */
export const registeredNamespaces = new Set<string>();

/**
 * Development-only map of emitted class name → owner key. Two different owners
 * producing the same class string means rules will overwrite each other —
 * either a cross-scope semantic collision or a hash collision in
 * `hashed`/`compact` mode.
 */
const emittedClassNameOwners = new Map<string, string>();

function isDev(): boolean {
  return typeof process === 'undefined' || process.env.NODE_ENV !== 'production';
}

/**
 * Track an emitted class name and warn when the same class string is produced
 * by two different style definitions. Development-only; no-op in production.
 *
 * The owner key identifies the logical definition (`scope:namespace` for
 * `styles.class` / `styles.component`, payload-derived for `styles.hashClass`)
 * so HMR re-registrations of the same definition are not flagged.
 */
export function trackEmittedClassName(className: string, ownerKey: string): void {
  if (!isDev()) return;
  const existing = emittedClassNameOwners.get(className);
  if (existing !== undefined && existing !== ownerKey) {
    console.error(
      `[typestyles] Class name collision: ".${className}" is generated by two different ` +
        `style definitions (${existing} and ${ownerKey}). Their CSS rules will overwrite ` +
        `each other. Use distinct namespaces, or isolate each package/file with ` +
        `createStyles({ scopeId: '…' }) (or fileScopeId(import.meta)).`,
    );
    return;
  }
  emittedClassNameOwners.set(className, ownerKey);
}

/** Clear collision tracking. Used by `reset()` in tests. */
export function resetEmittedClassNameTracking(): void {
  emittedClassNameOwners.clear();
  warnedUnscopedNamespaces.clear();
}

/**
 * Namespaces that have already emitted an unscoped-collision warning.
 * Prevents duplicate warnings for the same namespace during a session.
 */
const warnedUnscopedNamespaces = new Set<string>();

/**
 * Dev-mode warning when the same namespace is registered more than once
 * without a `scopeId`. Two unscoped registrations of the same namespace
 * produce identical class names whose CSS rules silently overwrite each
 * other. Emits once per namespace.
 */
export function warnUnscopedCollision(namespace: string, apiName: string): void {
  if (!isDev()) return;
  if (warnedUnscopedNamespaces.has(namespace)) return;
  warnedUnscopedNamespaces.add(namespace);
  console.warn(
    `[typestyles] ${apiName}('${namespace}', …) was registered more than once without a ` +
      `scopeId. Their CSS rules will overwrite each other. Isolate each definition with ` +
      `createStyles({ scopeId: '…' }) or createTypeStyles({ scopeId: '…' }). ` +
      `If this is caused by HMR re-execution, this warning is safe to ignore.`,
  );
}

const COLON = ':';

/**
 * Drop reserved `scopeId:namespace` keys so a module can re-register after HMR.
 * `namespace` is the first argument to `styles.component()` / `styles.class()` (not the scope).
 */
export function releaseReservedNamespacesForComponentOrClassNames(
  namespaces: readonly string[],
): void {
  if (namespaces.length === 0) return;
  const wanted = new Set(namespaces);
  const toRemove: string[] = [];
  for (const key of registeredNamespaces) {
    const i = key.indexOf(COLON);
    if (i === -1) continue;
    if (wanted.has(key.slice(i + 1))) {
      toRemove.push(key);
    }
  }
  for (const key of toRemove) {
    registeredNamespaces.delete(key);
  }
}

/** Vite plugin passes `.${namespace}-` prefixes for `styles.component()` invalidation. */
export function namespacesFromTypestylesHmrPrefixes(prefixes: readonly string[]): string[] {
  const out: string[] = [];
  for (const p of prefixes) {
    if (p.length >= 2 && p.startsWith('.') && p.endsWith('-')) {
      out.push(p.slice(1, -1));
    }
  }
  return out;
}
