import { describe, expect, it } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Types are generated by `scripts/build-playground-assets.mts`.
 * This test verifies the generator produces a usable manifest when present,
 * and documents the required keys when the asset has been built.
 */
describe('playground types manifest', () => {
  const typesPath = join(
    dirname(fileURLToPath(import.meta.url)),
    '../../../public/playground/types.json',
  );

  it('includes typestyles and react declaration entry points when built', () => {
    if (!existsSync(typesPath)) {
      // Asset is gitignored and built on astro dev/build — skip in cold CI without build.
      return;
    }

    const manifest = JSON.parse(readFileSync(typesPath, 'utf8')) as Record<string, string>;

    expect(manifest['file:///node_modules/typestyles/index.d.ts']).toContain('createTypeStyles');
    expect(manifest['file:///node_modules/@typestyles/react/index.d.ts']).toContain('createStyled');
    expect(manifest['file:///node_modules/react/index.d.ts'] ?? '').toMatch(/useState|React/);
    expect(manifest['file:///node_modules/csstype/index.d.ts']).toContain('Properties');
  });
});
