import { tokens } from 'typestyles';

export const colors = tokens.create('color', {
  border: 'hsl(214.3 31.8% 91.4%)',
  input: 'hsl(214.3 31.8% 91.4%)',
  ring: 'hsl(222.2 84% 4.9%)',
  background: 'hsl(0 0% 100%)',
  foreground: 'hsl(222.2 47.4% 11.2%)',
  primary: 'hsl(222.2 47.4% 11.2%)',
  primaryForeground: 'hsl(210 40% 98%)',
  secondary: 'hsl(210 40% 96.1%)',
  secondaryForeground: 'hsl(222.2 47.4% 11.2%)',
  destructive: 'hsl(0 84.2% 60.2%)',
  destructiveForeground: 'hsl(210 40% 98%)',
  muted: 'hsl(210 40% 96.1%)',
  mutedForeground: 'hsl(215.4 16.3% 46.9%)',
  accent: 'hsl(210 40% 96.1%)',
  accentForeground: 'hsl(222.2 47.4% 11.2%)',
  popover: 'hsl(0 0% 100%)',
  popoverForeground: 'hsl(222.2 84% 4.9%)',
  card: 'hsl(0 0% 100%)',
  cardForeground: 'hsl(222.2 84% 4.9%)',
  cardBorder: 'hsl(214.3 31.8% 91.4%)',
});

export const darkColors = tokens.create('dark-color', {
  border: 'hsl(0 0% 28%)',
  input: 'hsl(0 0% 22%)',
  ring: 'hsl(0 0% 83.9%)',
  background: 'hsl(0 0% 3.9%)',
  foreground: 'hsl(0 0% 98%)',
  primary: 'hsl(0 0% 98%)',
  primaryForeground: 'hsl(0 0% 9%)',
  secondary: 'hsl(0 0% 22%)',
  secondaryForeground: 'hsl(0 0% 98%)',
  destructive: 'hsl(0 62.8% 40%)',
  destructiveForeground: 'hsl(0 0% 98%)',
  muted: 'hsl(0 0% 18%)',
  mutedForeground: 'hsl(0 0% 63.9%)',
  accent: 'hsl(0 0% 22%)',
  accentForeground: 'hsl(0 0% 98%)',
  popover: 'hsl(0 0% 3.9%)',
  popoverForeground: 'hsl(0 0% 98%)',
  card: 'hsl(0 0% 5%)',
  cardForeground: 'hsl(0 0% 98%)',
  cardBorder: 'hsl(0 0% 22%)',
});

export const spacing = tokens.create('space', {
  0.5: '0.125rem',
  1: '0.25rem',
  1.5: '0.375rem',
  2: '0.5rem',
  2.5: '0.625rem',
  3: '0.75rem',
  3.5: '0.875rem',
  4: '1rem',
  5: '1.25rem',
  6: '1.5rem',
  7: '1.75rem',
  8: '2rem',
  9: '2.25rem',
  10: '2.5rem',
  11: '2.75rem',
  12: '3rem',
  14: '3.5rem',
  16: '4rem',
  20: '5rem',
  24: '6rem',
});

export const fontSize = tokens.create('font-size', {
  xs: '0.75rem',
  sm: '0.875rem',
  base: '1rem',
  lg: '1.125rem',
  xl: '1.25rem',
  '2xl': '1.5rem',
  '3xl': '1.875rem',
  '4xl': '2.25rem',
  '5xl': '3rem',
  '6xl': '3.75rem',
  '7xl': '4.5rem',
  '8xl': '6rem',
  '9xl': '8rem',
});

export const borderRadius = tokens.create('radius', {
  sm: 'calc(0.625rem - 2px)',
  DEFAULT: 'calc(0.625rem - 1px)',
  lg: '0.75rem',
  md: 'calc(0.625rem - 2px)',
  smpx: '4px',
});

export const lightTheme = tokens.createTheme('theme-light', {
  color: {
    border: colors.border,
    input: colors.input,
    ring: colors.ring,
    background: colors.background,
    foreground: colors.foreground,
    primary: colors.primary,
    primaryForeground: colors.primaryForeground,
    secondary: colors.secondary,
    secondaryForeground: colors.secondaryForeground,
    destructive: colors.destructive,
    destructiveForeground: colors.destructiveForeground,
    muted: colors.muted,
    mutedForeground: colors.mutedForeground,
    accent: colors.accent,
    accentForeground: colors.accentForeground,
    popover: colors.popover,
    popoverForeground: colors.popoverForeground,
    card: colors.card,
    cardForeground: colors.cardForeground,
    cardBorder: colors.cardBorder,
  },
});

export const darkTheme = tokens.createTheme('theme-dark', {
  color: {
    border: darkColors.border,
    input: darkColors.input,
    ring: darkColors.ring,
    background: darkColors.background,
    foreground: darkColors.foreground,
    primary: darkColors.primary,
    primaryForeground: darkColors.primaryForeground,
    secondary: darkColors.secondary,
    secondaryForeground: darkColors.secondaryForeground,
    destructive: darkColors.destructive,
    destructiveForeground: darkColors.destructiveForeground,
    muted: darkColors.muted,
    mutedForeground: darkColors.mutedForeground,
    accent: darkColors.accent,
    accentForeground: darkColors.accentForeground,
    popover: darkColors.popover,
    popoverForeground: darkColors.popoverForeground,
    card: darkColors.card,
    cardForeground: darkColors.cardForeground,
    cardBorder: darkColors.cardBorder,
  },
});
