import { designTokens as t } from '@examples/design-system';
import { styles } from './typestyles';

const bp = '@media (max-width: 768px)';
const desktop = '@media (min-width: 769px)';

/** Fluid hero scale — tight on mobile, generous on desktop, never sub-readable. */
const heroTitleSize = 'clamp(2.25rem, 6vw + 0.75rem, 4rem)';

export const home = styles.component(
  'docs-home',
  {
    hero: {
      position: 'relative',
      paddingTop: t.space[12],
      paddingBottom: t.space[8],
      overflow: 'hidden',
      [bp]: {
        paddingTop: t.space[8],
        paddingBottom: t.space[6],
      },
    },
    heroGrid: {
      position: 'absolute',
      inset: 0,
      backgroundImage: `radial-gradient(circle at 1px 1px, ${t.color.border.default} 1px, transparent 0)`,
      backgroundSize: '28px 28px',
      opacity: 0.4,
      pointerEvents: 'none',
      /** Focal point aligned with the left-aligned hero copy, not dead-center. */
      maskImage: 'radial-gradient(ellipse 80% 70% at 30% 0%, black 20%, transparent 75%)',
    },
    heroInner: {
      position: 'relative',
      zIndex: 1,
    },
    heroTop: {
      display: 'grid',
      gap: t.space[12],
      alignItems: 'start',
      [desktop]: {
        gridTemplateColumns: 'minmax(0, 1fr) minmax(320px, 520px)',
        gap: t.space[12],
        alignItems: 'center',
      },
    },
    heroCopy: {
      display: 'flex',
      flexDirection: 'column',
      gap: t.space[5],
      alignItems: 'flex-start',
    },
    eyebrow: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: t.space[2],
      fontSize: t.fontSize.sm,
      fontWeight: t.fontWeight.semibold,
      letterSpacing: '0.06em',
      textTransform: 'uppercase',
      color: t.color.text.secondary,
      margin: 0,
    },
    eyebrowDot: {
      width: '6px',
      height: '6px',
      borderRadius: t.radius.full,
      backgroundColor: t.color.accent.default,
    },
    title: {
      fontFamily: t.fontFamily.display,
      fontStyle: 'italic',
      fontSize: heroTitleSize,
      fontWeight: t.fontWeight.bold,
      letterSpacing: '-0.02em',
      lineHeight: 1.08,
      margin: 0,
      color: t.color.text.primary,
      textWrap: 'balance',
    },
    /** `real CSS` literally rendered in mono so the visual pun lands. */
    titleAccent: {
      fontFamily: t.fontFamily.mono,
      fontStyle: 'normal',
      fontSize: '0.82em',
      fontWeight: t.fontWeight.bold,
      letterSpacing: '-0.01em',
      paddingInline: t.space[3],
      paddingBlock: '0.05em',
      display: 'inline-block',
      boxDecorationBreak: 'clone',
      border: t.stroke.strong,
      backgroundColor: t.color.background.surface,
      verticalAlign: '0.08em',
    },
    subtitle: {
      fontSize: t.fontSize.xl,
      color: t.color.text.secondary,
      lineHeight: t.lineHeight.relaxed,
      maxWidth: '36rem',
      margin: 0,
      textWrap: 'pretty',
    },
    installChip: {
      display: 'inline-flex',
      alignItems: 'stretch',
      maxWidth: '100%',
      border: t.stroke.strong,
      backgroundColor: t.color.background.surface,
      boxShadow: t.shadow.md,
      fontFamily: t.fontFamily.mono,
      fontSize: t.fontSize.md,
    },
    installChipPre: {
      margin: 0,
      padding: `${t.space[3]} ${t.space[4]}`,
      display: 'flex',
      alignItems: 'center',
      overflow: 'auto',
      color: t.color.text.primary,
      whiteSpace: 'nowrap',
      '&::before': {
        content: '"$"',
        color: t.color.text.secondary,
        marginRight: t.space[2],
        userSelect: 'none',
      },
      '& code': {
        fontFamily: 'inherit',
        fontSize: 'inherit',
        background: 'none',
        padding: 0,
      },
    },
    installChipCopy: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: `0 ${t.space[4]}`,
      borderLeft: t.stroke.strong,
      borderTop: 0,
      borderRight: 0,
      borderBottom: 0,
      background: t.color.background.subtle,
      color: t.color.text.primary,
      fontFamily: t.fontFamily.mono,
      fontSize: t.fontSize.xs,
      fontWeight: t.fontWeight.semibold,
      letterSpacing: '0.04em',
      textTransform: 'uppercase',
      cursor: 'pointer',
      transition: 'background-color 120ms ease',
      '&:hover:not(:disabled)': {
        backgroundColor: t.color.accent.subtle,
      },
      '&[data-copied="true"]': {
        backgroundColor: t.color.accent.default,
        color: t.color.text.onAccent,
      },
    },
    actions: {
      display: 'flex',
      alignItems: 'center',
      gap: t.space[3],
      flexWrap: 'wrap',
      [bp]: {
        flexDirection: 'column',
        alignItems: 'stretch',
        width: '100%',
      },
    },
    cta: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: t.space[2],
      fontSize: t.fontSize.lg,
      fontWeight: t.fontWeight.bold,
      fontFamily: t.fontFamily.sans,
      color: t.color.text.onAccent,
      backgroundColor: t.color.accent.default,
      padding: `12px ${t.space[5]}`,
      textDecoration: 'none',
      border: `${t.borderWidth.default} solid ${t.color.border.default}`,
      boxShadow: t.shadow.md,
      cursor: 'pointer',
      textTransform: 'uppercase',
      letterSpacing: '0.02em',
      '&:hover': {
        transform: 'translate(2px, 2px)',
        boxShadow: t.shadow.xs,
      },
      '&:active': {
        transform: 'translate(4px, 4px)',
        boxShadow: 'none',
      },
    },
    ctaSecondary: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: t.space[2],
      fontSize: t.fontSize.lg,
      fontWeight: t.fontWeight.bold,
      fontFamily: t.fontFamily.sans,
      color: t.color.text.primary,
      backgroundColor: t.color.background.surface,
      padding: `12px ${t.space[5]}`,
      textDecoration: 'none',
      border: `${t.borderWidth.default} solid ${t.color.border.default}`,
      boxShadow: t.shadow.md,
      cursor: 'pointer',
      textTransform: 'uppercase',
      letterSpacing: '0.02em',
      '&:hover': {
        transform: 'translate(2px, 2px)',
        boxShadow: t.shadow.xs,
      },
      '&:active': {
        transform: 'translate(4px, 4px)',
        boxShadow: 'none',
      },
    },
    metaRow: {
      display: 'flex',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: `${t.space[2]} ${t.space[3]}`,
      fontFamily: t.fontFamily.mono,
      fontSize: t.fontSize.xs,
      color: t.color.text.secondary,
      letterSpacing: '0.04em',
      textTransform: 'uppercase',
    },
    metaDivider: {
      display: 'inline-block',
      width: '4px',
      height: '4px',
      backgroundColor: t.color.border.default,
      opacity: 0.5,
    },
    codeExampleWrap: {
      width: '100%',
      maxWidth: '100%',
      [desktop]: {
        justifySelf: 'end',
      },
    },
    section: {
      paddingTop: t.space[12],
      paddingBottom: t.space[12],
      borderTop: t.stroke.default,
      [bp]: {
        paddingTop: t.space[8],
        paddingBottom: t.space[8],
      },
    },
    /** Denser rhythm on the benefits block to break cadence with the split sections. */
    sectionDense: {
      paddingTop: t.space[8],
      paddingBottom: t.space[8],
      [bp]: {
        paddingTop: t.space[6],
        paddingBottom: t.space[6],
      },
    },
    sectionHead: {
      maxWidth: '40rem',
      marginBottom: t.space[8],
    },
    sectionKicker: {
      fontSize: t.fontSize.sm,
      fontWeight: t.fontWeight.semibold,
      letterSpacing: '0.08em',
      textTransform: 'uppercase',
      color: t.color.accent.default,
      marginBottom: t.space[2],
      fontFamily: t.fontFamily.mono,
    },
    sectionTitle: {
      fontSize: t.fontSize['2xl'],
      fontWeight: t.fontWeight.bold,
      letterSpacing: '-0.02em',
      lineHeight: 1.2,
      color: t.color.text.primary,
      margin: 0,
      marginBottom: t.space[3],
      fontFamily: t.fontFamily.display,
      fontStyle: 'italic',
    },
    sectionLead: {
      fontSize: t.fontSize.lg,
      color: t.color.text.secondary,
      lineHeight: t.lineHeight.relaxed,
      margin: 0,
    },
    /** Asymmetric benefits: one hero card, three smaller cards. */
    benefitStack: {
      display: 'flex',
      flexDirection: 'column',
      gap: t.space[4],
    },
    benefitHero: {
      display: 'grid',
      gap: t.space[6],
      padding: t.space[8],
      border: t.stroke.strong,
      backgroundColor: t.color.background.surface,
      boxShadow: t.shadow.lg,
      alignItems: 'center',
      [desktop]: {
        gridTemplateColumns: 'minmax(0, 1fr) minmax(320px, 480px)',
        gap: t.space[8],
      },
      [bp]: {
        padding: t.space[5],
      },
    },
    benefitHeroCopy: {
      display: 'flex',
      flexDirection: 'column',
      gap: t.space[3],
    },
    benefitHeroTitle: {
      fontSize: t.fontSize['2xl'],
      fontFamily: t.fontFamily.display,
      fontStyle: 'italic',
      fontWeight: t.fontWeight.bold,
      letterSpacing: '-0.02em',
      lineHeight: 1.15,
      color: t.color.text.primary,
      margin: 0,
    },
    benefitHeroText: {
      fontSize: t.fontSize.lg,
      color: t.color.text.secondary,
      lineHeight: t.lineHeight.relaxed,
      margin: 0,
      '& code': {
        fontFamily: t.fontFamily.mono,
        fontSize: '0.9em',
        padding: `0 ${t.space[1]}`,
        backgroundColor: t.color.background.subtle,
      },
    },
    /** DOM preview showing actual class names on the page — the whole selling point. */
    classPreview: {
      display: 'flex',
      flexDirection: 'column',
      gap: t.space[2],
      padding: t.space[4],
      border: t.stroke.default,
      backgroundColor: t.color.background.app,
      fontFamily: t.fontFamily.mono,
      fontSize: t.fontSize.sm,
      color: t.color.text.primary,
      overflow: 'auto',
    },
    classPreviewLine: {
      whiteSpace: 'pre',
    },
    classPreviewLabel: {
      fontSize: t.fontSize.xs,
      fontWeight: t.fontWeight.semibold,
      letterSpacing: '0.06em',
      textTransform: 'uppercase',
      color: t.color.text.secondary,
      marginBottom: t.space[1],
    },
    classPreviewToken: {
      color: t.color.accent.default,
    },
    benefitRow: {
      display: 'grid',
      gap: t.space[4],
      gridTemplateColumns: '1fr',
      [desktop]: {
        gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
      },
    },
    benefitCard: {
      display: 'flex',
      flexDirection: 'column',
      gap: t.space[2],
      padding: t.space[5],
      border: t.stroke.default,
      backgroundColor: t.color.background.surface,
      boxShadow: t.shadow.xs,
      transition: 'transform 120ms ease, box-shadow 120ms ease',
      '&:hover': {
        transform: 'translate(-1px, -1px)',
        boxShadow: t.shadow.sm,
      },
    },
    benefitNumber: {
      fontFamily: t.fontFamily.mono,
      fontSize: t.fontSize.xs,
      fontWeight: t.fontWeight.semibold,
      letterSpacing: '0.1em',
      color: t.color.accent.default,
      marginBottom: t.space[1],
    },
    benefitTitle: {
      fontSize: t.fontSize.lg,
      fontWeight: t.fontWeight.semibold,
      color: t.color.text.primary,
      margin: 0,
      lineHeight: 1.3,
    },
    benefitText: {
      fontSize: t.fontSize.md,
      color: t.color.text.secondary,
      lineHeight: 1.55,
      margin: 0,
      '& code': {
        fontFamily: t.fontFamily.mono,
        fontSize: '0.9em',
        padding: `0 ${t.space[1]}`,
        backgroundColor: t.color.background.subtle,
      },
    },
    split: {
      display: 'grid',
      gap: t.space[8],
      alignItems: 'center',
      [desktop]: {
        gridTemplateColumns: '1fr 1fr',
        gap: t.space[12],
      },
    },
    /** Desktop: visual column order without duplicate markup (default: prose then media). */
    splitProseFirst: {
      [desktop]: { order: 1 },
    },
    splitMediaSecond: {
      [desktop]: { order: 2 },
    },
    splitProseSecond: {
      [desktop]: { order: 2 },
    },
    splitMediaFirst: {
      [desktop]: { order: 1 },
    },
    proseList: {
      margin: 0,
      paddingLeft: t.space[5],
      color: t.color.text.secondary,
      fontSize: t.fontSize.md,
      lineHeight: 1.65,
      display: 'flex',
      flexDirection: 'column',
      gap: t.space[3],
    },
    integrations: {
      display: 'flex',
      flexWrap: 'wrap',
      gap: t.space[3],
      alignItems: 'center',
      justifyContent: 'center',
      paddingTop: t.space[4],
    },
    integrationChip: {
      fontSize: t.fontSize.sm,
      fontWeight: t.fontWeight.semibold,
      color: t.color.text.primary,
      backgroundColor: t.color.background.surface,
      border: t.stroke.default,
      borderRadius: t.radius.md,
      padding: `${t.space[2]} ${t.space[4]}`,
    },
    /** Brutalist CTA band: flat paper surface, thick ink border, hard shadow offset. */
    ctaBand: {
      marginTop: t.space[4],
      padding: t.space[12],
      border: t.stroke.strong,
      backgroundColor: t.color.background.surface,
      boxShadow: t.shadow.xl,
      textAlign: 'center',
      [bp]: {
        padding: `${t.space[8]} ${t.space[5]}`,
        boxShadow: t.shadow.lg,
      },
    },
    ctaBandTitle: {
      fontFamily: t.fontFamily.display,
      fontStyle: 'italic',
      fontSize: t.fontSize['2xl'],
      fontWeight: t.fontWeight.bold,
      color: t.color.text.primary,
      margin: 0,
      marginBottom: t.space[3],
      letterSpacing: '-0.02em',
    },
    ctaBandLead: {
      fontSize: t.fontSize.lg,
      color: t.color.text.secondary,
      margin: '0 auto',
      marginBottom: t.space[6],
      maxWidth: '32rem',
      lineHeight: t.lineHeight.relaxed,
    },
    ctaBandActions: {
      display: 'flex',
      justifyContent: 'center',
      gap: t.space[4],
      flexWrap: 'wrap',
      [bp]: {
        flexDirection: 'column',
        alignItems: 'stretch',
      },
    },
    ghIcon: {
      display: 'inline-flex',
      alignItems: 'center',
    },
  },
  { layer: 'components' },
);
