import { designTokens as t } from '@examples/design-system';
import { docsTokens as dt, styles } from './typestyles';

const bp = '@media (max-width: 768px)';

export const home = styles.component('docs-home', {
  hero: {
    paddingTop: t.space[12],
    paddingBottom: t.space[8],
    [bp]: {
      paddingTop: t.space[8],
    },
  },
  title: {
    fontSize: dt.size.heroTitle,
    fontWeight: t.fontWeight.bold,
    letterSpacing: '-0.035em',
    lineHeight: 1.1,
    marginBottom: t.space[4],
    color: t.color.text.primary,
    [bp]: {
      fontSize: dt.size.titleLarge,
    },
  },
  titleAccent: {
    backgroundColor: t.color.accent.default,
    color: t.color.text.onAccent,
    padding: `0 ${t.space[2]}`,
    display: 'inline',
    boxDecorationBreak: 'clone',
  },
  subtitle: {
    fontSize: dt.size.subtitle,
    color: t.color.text.secondary,
    lineHeight: t.lineHeight.relaxed,
    maxWidth: dt.size.subtitleMaxWidth,
    marginBottom: t.space[6],
  },
  actions: {
    display: 'flex',
    alignItems: 'center',
    gap: t.space[4],
    marginBottom: t.space[8],
    [bp]: {
      flexDirection: 'column',
      alignItems: 'flex-start',
    },
  },
  cta: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: t.space[2],
    fontSize: dt.size.ctaText,
    fontWeight: t.fontWeight.bold,
    fontFamily: t.fontFamily.sans,
    color: '#000',
    backgroundColor: t.color.accent.default,
    padding: `12px ${t.space[5]}`,
    textDecoration: 'none',
    border: `${t.borderWidth.default} solid #000`,
    boxShadow: t.shadow.md,
    cursor: 'pointer',
    textTransform: 'uppercase',
    letterSpacing: '0.02em',
    '&:hover': {
      transform: 'translate(2px, 2px)',
      boxShadow: `2px 2px 0 0 #000`,
    },
    '&:active': {
      transform: 'translate(4px, 4px)',
      boxShadow: 'none',
    },
  },
  ctaSecondary: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: t.space[2],
    fontSize: dt.size.ctaText,
    fontWeight: t.fontWeight.bold,
    fontFamily: t.fontFamily.sans,
    color: t.color.text.primary,
    backgroundColor: t.color.background.surface,
    padding: `12px ${t.space[5]}`,
    textDecoration: 'none',
    border: `${t.borderWidth.default} solid #000`,
    boxShadow: t.shadow.md,
    cursor: 'pointer',
    textTransform: 'uppercase',
    letterSpacing: '0.02em',
    '&:hover': {
      transform: 'translate(2px, 2px)',
      boxShadow: `2px 2px 0 0 #000`,
    },
    '&:active': {
      transform: 'translate(4px, 4px)',
      boxShadow: 'none',
    },
  },
  codeExample: {
    maxWidth: '520px',
    border: `${t.borderWidth.default} solid #000`,
    boxShadow: t.shadow.lg,
    overflow: 'hidden',
  },
  codeExampleHeader: {
    padding: `${t.space[2]} ${t.space[4]}`,
    backgroundColor: t.color.background.subtle,
    borderBottom: `${t.borderWidth.default} solid #000`,
    fontSize: t.fontSize.xs,
    fontWeight: t.fontWeight.bold,
    fontFamily: t.fontFamily.mono,
    color: t.color.text.secondary,
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
  },
  codeExampleBody: {
    padding: t.space[4],
    backgroundColor: t.color.background.surface,
    fontFamily: t.fontFamily.mono,
    fontSize: t.fontSize.sm,
    lineHeight: 1.6,
    color: t.color.text.primary,
    whiteSpace: 'pre',
    overflowX: 'auto',
  },
});
