import { designTokens as t } from '@examples/design-system';
import { styles } from './typestyles';

export const liveDemo = styles.component(
  'docs-live-demo',
  {
    root: {
      marginTop: t.space[6],
      marginBottom: t.space[8],
      minWidth: 0,
      border: `1px solid ${t.color.border.default}`,
      borderRadius: t.radius.lg,
      overflow: 'hidden',
      backgroundColor: t.color.surface.default,
    },
    header: {
      display: 'flex',
      flexWrap: 'wrap',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: t.space[3],
      padding: `${t.space[4]} ${t.space[4]} ${t.space[3]}`,
      borderBottom: `1px solid ${t.color.border.default}`,
      backgroundColor: t.color.surface.sunken,
    },
    headerText: {
      display: 'flex',
      flexDirection: 'column',
      gap: t.space[1],
      minWidth: 0,
      flex: '1 1 12rem',
    },
    title: {
      margin: 0,
      fontSize: t.fontSize.sm,
      fontWeight: t.fontWeight.semibold,
      color: t.color.text.primary,
    },
    caption: {
      margin: 0,
      fontSize: t.fontSize.xs,
      lineHeight: 1.45,
      color: t.color.text.secondary,
      maxWidth: '42ch',
    },
    variantList: {
      display: 'flex',
      flexWrap: 'wrap',
      gap: t.space[2],
      flexShrink: 0,
    },
    variantButton: {
      padding: `${t.space[1]} ${t.space[3]}`,
      fontSize: t.fontSize.xs,
      fontWeight: t.fontWeight.medium,
      border: `1px solid ${t.color.border.default}`,
      borderRadius: t.radius.md,
      backgroundColor: t.color.surface.default,
      color: t.color.text.secondary,
      cursor: 'pointer',
      transition: 'border-color 120ms ease, color 120ms ease, background-color 120ms ease',
      '&[data-active="true"]': {
        borderColor: t.color.accent.default,
        color: t.color.accent.default,
        backgroundColor: t.color.accent.subtle,
      },
    },
    preview: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: '96px',
      padding: `${t.space[5]} ${t.space[4]}`,
      borderBottom: `1px solid ${t.color.border.default}`,
      backgroundColor: t.color.surface.raised,
      backgroundImage: `linear-gradient(45deg, color-mix(in oklch, ${t.color.border.default} 22%, transparent) 25%, transparent 25%, transparent 75%, color-mix(in oklch, ${t.color.border.default} 22%, transparent) 75%, color-mix(in oklch, ${t.color.border.default} 22%, transparent)), linear-gradient(45deg, color-mix(in oklch, ${t.color.border.default} 22%, transparent) 25%, transparent 25%, transparent 75%, color-mix(in oklch, ${t.color.border.default} 22%, transparent) 75%, color-mix(in oklch, ${t.color.border.default} 22%, transparent))`,
      backgroundPosition: '0 0, 8px 8px',
      backgroundSize: '16px 16px',
    },
    previewButton: {
      font: 'inherit',
    },
    previewCard: {
      minWidth: '200px',
      textAlign: 'center',
      fontSize: t.fontSize.sm,
    },
    section: {
      padding: t.space[4],
      borderBottom: `1px solid ${t.color.border.default}`,
      minWidth: 0,
      '&:last-child': {
        borderBottom: 'none',
      },
    },
    sectionLabel: {
      margin: `0 0 ${t.space[2]}`,
      fontSize: t.fontSize.xs,
      fontWeight: t.fontWeight.semibold,
      letterSpacing: '0.06em',
      textTransform: 'uppercase',
      color: t.color.text.secondary,
    },
    sectionFile: {
      fontWeight: t.fontWeight.medium,
      color: t.color.text.primary,
      textTransform: 'none',
      letterSpacing: 'normal',
    },
    detailsGrid: {
      display: 'grid',
      gridTemplateColumns: '1fr 1fr',
      gap: 0,
      minWidth: 0,
      borderBottom: 'none',
      '@media (max-width: 560px)': {
        gridTemplateColumns: '1fr',
      },
    },
    detailSection: {
      padding: t.space[4],
      minWidth: 0,
      '&:first-child': {
        borderRight: `1px solid ${t.color.border.default}`,
        '@media (max-width: 560px)': {
          borderRight: 'none',
          borderBottom: `1px solid ${t.color.border.default}`,
        },
      },
    },
    codeShell: {
      margin: 0,
      borderRadius: t.radius.md,
      backgroundColor: t.codeBlock.background,
      overflow: 'auto',
      '& [data-codeblock-pre]': {
        margin: 0,
        padding: t.space[3],
        maxHeight: '260px',
        fontSize: t.fontSize.xs,
        lineHeight: 1.55,
        whiteSpace: 'pre',
        backgroundColor: 'transparent',
      },
      '& [data-codeblock] code': {
        fontFamily: 'inherit',
        fontSize: 'inherit',
        fontWeight: 'inherit',
        color: 'inherit',
        backgroundColor: 'transparent',
        padding: 0,
        borderRadius: 0,
        border: 'none',
      },
    },
    outputShell: {
      maxHeight: '200px',
    },
  },
  { layer: 'components' },
);
