import { designTokens as t } from '@examples/design-system';
import { styles } from './typestyles';

const desktop = '@media (min-width: 900px)';
/** Match docs fixed header offset (`docs/src/styles/layout.ts`). */
const siteHeaderHeight = `calc(${t.space[8]} + ${t.space[2]})`;

export const playground = styles.component(
  'docs-playground',
  {
    page: {
      display: 'flex',
      flexDirection: 'column',
      minHeight: '100vh',
      paddingTop: siteHeaderHeight,
      backgroundColor: t.color.background.app,
      color: t.color.text.primary,
    },
    toolbar: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: t.space[4],
      flexWrap: 'wrap',
      padding: `${t.space[2]} ${t.space[4]}`,
      borderBottom: `1px solid ${t.color.border.default}`,
      backgroundColor: t.color.surface.sunken,
    },
    toolbarLeft: {
      display: 'flex',
      alignItems: 'center',
      gap: t.space[3],
      minWidth: 0,
    },
    toolbarRight: {
      display: 'flex',
      alignItems: 'center',
      gap: t.space[3],
      flexWrap: 'wrap',
    },
    presetLabel: {
      display: 'flex',
      alignItems: 'center',
      gap: t.space[2],
      fontSize: t.fontSize.xs,
      color: t.color.text.secondary,
    },
    presetSelect: {
      fontFamily: t.fontFamily.mono,
      fontSize: t.fontSize.sm,
      padding: `${t.space[1]} ${t.space[2]}`,
      borderRadius: t.radius.md,
      border: `1px solid ${t.color.border.default}`,
      backgroundColor: t.color.background.elevated,
      color: t.color.text.primary,
      minWidth: '10rem',
    },
    shareButton: {
      appearance: 'none',
      fontFamily: t.fontFamily.mono,
      fontSize: t.fontSize.sm,
      padding: `${t.space[1]} ${t.space[3]}`,
      borderRadius: t.radius.md,
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: t.color.border.default,
      backgroundColor: t.color.background.elevated,
      color: t.color.text.primary,
      cursor: 'pointer',
      '&:hover': {
        borderColor: t.color.accent.default,
        color: t.color.accent.default,
      },
    },
    workspace: {
      display: 'flex',
      flex: '1 1 auto',
      flexDirection: 'column',
      minHeight: 0,
      [desktop]: {
        flexDirection: 'row',
      },
    },
    editorPane: {
      display: 'flex',
      flexDirection: 'column',
      flex: '1 1 50%',
      minWidth: 0,
      minHeight: '18rem',
      borderBottom: `1px solid ${t.color.border.default}`,
      [desktop]: {
        borderBottom: 'none',
        borderRight: `1px solid ${t.color.border.default}`,
      },
    },
    editorTabBar: {
      display: 'flex',
      alignItems: 'center',
      gap: t.space[2],
      padding: `${t.space[2]} ${t.space[3]}`,
      borderBottom: `1px solid ${t.color.border.default}`,
      backgroundColor: t.color.surface.sunken,
      fontFamily: t.fontFamily.mono,
      fontSize: t.fontSize.xs,
      color: t.color.text.secondary,
    },
    editorHost: {
      flex: '1 1 auto',
      minHeight: 0,
    },
    outputPane: {
      display: 'flex',
      flexDirection: 'column',
      flex: '1 1 50%',
      minWidth: 0,
      minHeight: '16rem',
    },
    tabBar: {
      display: 'flex',
      alignItems: 'stretch',
      gap: 0,
      borderBottom: `1px solid ${t.color.border.default}`,
      backgroundColor: t.color.surface.sunken,
    },
    tab: {
      appearance: 'none',
      background: 'transparent',
      padding: `${t.space[2]} ${t.space[4]}`,
      fontFamily: t.fontFamily.mono,
      fontSize: t.fontSize.xs,
      color: t.color.text.secondary,
      cursor: 'pointer',
      borderTopWidth: 0,
      borderLeftWidth: 0,
      borderRightWidth: 0,
      borderBottomWidth: '2px',
      borderStyle: 'solid',
      borderColor: 'transparent',
      marginBottom: '-1px',
    },
    tabActive: {
      color: t.color.text.primary,
      borderBottomColor: t.color.accent.default,
      backgroundColor: t.color.background.surface,
    },
    panel: {
      display: 'none',
      flex: '1 1 auto',
      minHeight: 0,
      overflow: 'auto',
    },
    panelActive: {
      display: 'flex',
      flexDirection: 'column',
    },
    previewFrame: {
      flex: '1 1 auto',
      width: '100%',
      minHeight: '12rem',
      border: 'none',
      backgroundColor: '#fff',
    },
    cssEditorHost: {
      flex: '1 1 auto',
      minHeight: 0,
      width: '100%',
    },
    codePanel: {
      margin: 0,
      padding: t.space[4],
      fontFamily: t.fontFamily.mono,
      fontSize: t.fontSize.xs,
      lineHeight: 1.55,
      whiteSpace: 'pre-wrap',
      wordBreak: 'break-word',
      color: t.color.text.primary,
      backgroundColor: t.color.background.surface,
      flex: '1 1 auto',
      overflow: 'auto',
    },
    errorPanel: {
      margin: 0,
      padding: t.space[4],
      fontFamily: t.fontFamily.mono,
      fontSize: t.fontSize.xs,
      lineHeight: 1.55,
      whiteSpace: 'pre-wrap',
      wordBreak: 'break-word',
      color: t.color.danger.default,
      backgroundColor: t.color.background.surface,
      flex: '1 1 auto',
      overflow: 'auto',
    },
    emptyState: {
      padding: t.space[4],
      fontSize: t.fontSize.sm,
      color: t.color.text.secondary,
    },
    console: {
      borderTop: `1px solid ${t.color.border.default}`,
      backgroundColor: t.color.surface.sunken,
      maxHeight: '8rem',
      overflow: 'auto',
    },
    consoleHeader: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: `${t.space[1]} ${t.space[3]}`,
      fontFamily: t.fontFamily.mono,
      fontSize: '0.65rem',
      letterSpacing: '0.08em',
      textTransform: 'uppercase',
      color: t.color.text.secondary,
    },
    consoleBody: {
      margin: 0,
      padding: `0 ${t.space[3]} ${t.space[2]}`,
      fontFamily: t.fontFamily.mono,
      fontSize: t.fontSize.xs,
      lineHeight: 1.45,
      whiteSpace: 'pre-wrap',
      color: t.color.text.secondary,
    },
  },
  { layer: 'components' },
);

export const playgroundTab = styles.component(
  'docs-playground-tab',
  {
    root: playground.tab,
    active: {
      ...playground.tab,
      ...playground.tabActive,
    },
  },
  { layer: 'components' },
);

export const playgroundPanel = styles.component(
  'docs-playground-panel',
  {
    root: playground.panel,
    active: {
      ...playground.panel,
      ...playground.panelActive,
    },
  },
  { layer: 'components' },
);
