import { designTokens as t } from '@examples/design-system';
import { styles } from 'typestyles';

const bp = '@media (max-width: 768px)';

const sidebarBase = styles.component('docs-sidebar', {
  root: {
    width: '280px',
    flexShrink: 0,
    height: '100vh',
    position: 'sticky',
    top: 0,
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: t.color.background.subtle,
    borderRight: `1px solid ${t.color.border.default}`,
    transition: 'background-color 0.2s ease, border-color 0.2s ease',
    [bp]: {
      position: 'fixed',
      height: 'auto',
      top: 0,
      left: 0,
      bottom: 0,
      zIndex: 200,
      transform: 'translateX(-100%)',
      visibility: 'hidden',
      transition:
        'transform 0.25s ease, visibility 0.25s ease, background-color 0.2s ease, border-color 0.2s ease',
    },
  },
  rootOpen: {
    [bp]: {
      transform: 'translateX(0)',
      visibility: 'visible',
    },
  },
  backdrop: {
    display: 'none',
    [bp]: {
      display: 'block',
      position: 'fixed',
      inset: 0,
      zIndex: 100,
      backgroundColor: t.color.overlay.default,
      opacity: 0,
      visibility: 'hidden',
      transition: 'opacity 0.25s ease, visibility 0.25s ease',
    },
  },
  backdropVisible: {
    [bp]: {
      opacity: 1,
      visibility: 'visible',
    },
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    padding: `${t.space[5]} ${t.space[5]} ${t.space[4]}`,
  },
  logo: {
    fontSize: t.fontSize.xl,
    fontWeight: t.fontWeight.bold,
    color: t.color.text.primary,
    textDecoration: 'none',
    letterSpacing: '-0.03em',
    transition: 'color 0.15s ease',
    '&:hover': { color: t.color.accent.default },
  },
  logoAccent: {
    color: t.color.accent.default,
  },
  search: {
    margin: `0 ${t.space[4]} ${t.space[4]}`,
    padding: `${t.space[2]} ${t.space[4]}`,
    fontSize: t.fontSize.sm,
    fontFamily: t.fontFamily.sans,
    backgroundColor: t.color.background.subtle,
    border: `1px solid ${t.color.border.default}`,
    borderRadius: t.radius.md,
    color: t.color.text.secondary,
    outline: 'none',
    transition: 'border-color 0.15s ease, background-color 0.2s ease',
    '&:focus': { borderColor: t.color.accent.default },
    '&::placeholder': { color: t.color.text.placeholder },
  },
  searchWrapper: {
    position: 'relative',
    margin: `0 ${t.space[4]} ${t.space[4]}`,
  },
  searchIcon: {
    position: 'absolute',
    left: '10px',
    top: '50%',
    transform: 'translateY(-50%)',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: t.color.text.placeholder,
    pointerEvents: 'none',
    lineHeight: 0,
  },
  searchInput: {
    width: '100%',
    padding: `${t.space[2]} ${t.space[4]} ${t.space[2]} 32px`,
    fontSize: t.fontSize.sm,
    fontFamily: t.fontFamily.sans,
    backgroundColor: t.color.background.subtle,
    border: `1px solid ${t.color.border.default}`,
    borderRadius: t.radius.md,
    color: t.color.text.secondary,
    outline: 'none',
    transition: 'border-color 0.15s ease, background-color 0.2s ease',
    '&:focus': { borderColor: t.color.accent.default },
    '&::placeholder': { color: t.color.text.placeholder },
  },
  searchKbd: {
    position: 'absolute',
    right: '10px',
    top: '50%',
    transform: 'translateY(-50%)',
    fontSize: t.fontSize.xs,
    color: t.color.text.placeholder,
    backgroundColor: t.color.background.surface,
    border: `1px solid ${t.color.border.default}`,
    borderRadius: t.radius.sm,
    padding: `${t.space[1]} 5px`,
    fontFamily: t.fontFamily.sans,
    lineHeight: '16px',
    pointerEvents: 'none',
  },
  searchTrigger: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    margin: 0,
    padding: `${t.space[2]} ${t.space[4]} ${t.space[2]} 32px`,
    fontSize: t.fontSize.sm,
    fontFamily: t.fontFamily.sans,
    textAlign: 'left',
    cursor: 'pointer',
    backgroundColor: t.color.background.subtle,
    border: `1px solid ${t.color.border.default}`,
    borderRadius: t.radius.md,
    color: t.color.text.secondary,
    outline: 'none',
    transition: 'border-color 0.15s ease, background-color 0.2s ease',
    '&:hover': {
      borderColor: `color-mix(in srgb, ${t.color.accent.default} 45%, ${t.color.border.default})`,
      color: t.color.text.primary,
    },
    '&:focus-visible': {
      borderColor: t.color.accent.default,
      outline: `2px solid ${t.color.accent.default}`,
      outlineOffset: '2px',
    },
  },
  nav: {
    flex: 1,
    overflowY: 'auto',
    padding: `0 ${t.space[4]}`,
  },
  section: {
    marginBottom: t.space[2],
  },
  sectionTitle: {
    fontSize: t.fontSize.xs,
    fontWeight: t.fontWeight.semibold,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    color: t.color.text.placeholder,
    padding: `${t.space[2]} ${t.space[2]}`,
    marginTop: t.space[2],
  },
  link: {
    display: 'block',
    fontSize: t.fontSize.md,
    color: t.color.text.secondary,
    textDecoration: 'none',
    padding: `6px ${t.space[2]}`,
    borderRadius: t.radius.sm,
    transition: 'color 0.12s ease, background-color 0.12s ease',
    '&:hover': {
      color: t.color.text.primary,
      backgroundColor: t.color.background.subtle,
    },
  },
  linkActive: {
    color: t.color.accent.default,
    fontWeight: t.fontWeight.medium,
    backgroundColor: t.color.accent.subtle,
    '&:hover': {
      color: t.color.accent.default,
      backgroundColor: t.color.accent.subtle,
    },
  },
  footer: {
    padding: `${t.space[4]} ${t.space[5]}`,
    borderTop: `1px solid ${t.color.border.default}`,
    transition: 'border-color 0.2s ease',
    display: 'flex',
    flexDirection: 'column',
    gap: t.space[2],
  },
  themeFieldLabel: {
    fontSize: t.fontSize.xs,
    fontWeight: t.fontWeight.semibold,
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    color: t.color.text.placeholder,
  },
  themeSelect: {
    width: '100%',
    padding: `${t.space[2]} ${t.space[4]}`,
    fontSize: t.fontSize.sm,
    fontFamily: t.fontFamily.sans,
    backgroundColor: t.color.background.subtle,
    border: `1px solid ${t.color.border.default}`,
    borderRadius: t.radius.md,
    color: t.color.text.primary,
    cursor: 'pointer',
    outline: 'none',
    transition: 'border-color 0.15s ease, background-color 0.2s ease',
    '&:focus': { borderColor: t.color.accent.default },
  },
  themeToggle: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: t.space[2],
    width: '100%',
    padding: `7px ${t.space[4]}`,
    fontSize: t.fontSize.sm,
    color: t.color.text.secondary,
    backgroundColor: t.color.background.subtle,
    border: `1px solid ${t.color.border.default}`,
    borderRadius: t.radius.md,
    cursor: 'pointer',
    fontFamily: t.fontFamily.sans,
    transition: 'color 0.15s ease, border-color 0.15s ease, background-color 0.15s ease',
    '&:hover': {
      color: t.color.text.primary,
      borderColor: t.color.text.secondary,
    },
  },
});

export const sidebar = sidebarBase;
