import { designTokens as t } from '@examples/design-system';
import { styles } from './typestyles';

const desktop = '@media (min-width: 769px)';

const siteHeaderHeight = `calc(${t.space[8]} + ${t.space[2]})`;

export const siteHeader = styles.component(
  'docs-site-header',
  {
    root: {
      display: 'none',
      [desktop]: {
        display: 'block',
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        width: '100%',
        zIndex: 250,
        backgroundColor: t.color.background.app,
        borderBottom: `${t.borderWidth.thick} solid ${t.color.border.strong}`,
      },
    },
    inner: {
      display: 'flex',
      alignItems: 'stretch',
      justifyContent: 'space-between',
      gap: t.space[6],
      height: siteHeaderHeight,
      minHeight: siteHeaderHeight,
      padding: `0 ${t.space[6]}`,
      boxSizing: 'border-box',
    },
    left: {
      display: 'flex',
      alignItems: 'stretch',
      gap: t.space[8],
      minWidth: 0,
    },
    logo: {
      fontSize: t.fontSize.xl,
      fontWeight: t.fontWeight.bold,
      color: t.color.text.primary,
      textDecoration: 'none',
      letterSpacing: '-0.03em',
      textTransform: 'uppercase',
      flexShrink: 0,
      alignSelf: 'center',
      '&:hover': { color: t.color.accent.default },
    },
    logoAccent: {
      color: t.color.accent.default,
    },
    nav: {
      display: 'flex',
      alignItems: 'stretch',
      gap: 0,
      alignSelf: 'stretch',
      height: '100%',
    },
    /**
     * Sidebar/TOC-style type and colors. Current item: `::after` bar sits in the header’s bottom border lane
     * (translated past the link box) so it overlaps the root `border-bottom` instead of stacking above it.
     */
    navLink: {
      display: 'flex',
      alignItems: 'center',
      boxSizing: 'border-box',
      height: '100%',
      margin: 0,
      fontSize: t.fontSize.md,
      fontFamily: t.fontFamily.sans,
      lineHeight: 1.35,
      color: t.color.text.secondary,
      textDecoration: 'none',
      padding: `0 ${t.space[5]}`,
      border: 'none',
      backgroundColor: 'transparent',
      cursor: 'pointer',
      zIndex: 2,
      '&:hover': {
        color: t.color.text.primary,
        backgroundColor: t.color.background.subtle,
      },
      '&[aria-current="page"]': {
        position: 'relative',
        zIndex: 3,
        color: t.color.accent.default,
        fontWeight: t.fontWeight.medium,
        backgroundColor: t.color.accent.subtle,
        '&:hover': {
          color: t.color.accent.default,
          backgroundColor: t.color.accent.subtle,
        },
        '&::after': {
          content: '""',
          position: 'absolute',
          left: 0,
          right: 0,
          bottom: 0,
          height: t.borderWidth.thick,
          backgroundColor: t.color.accent.default,
          transform: 'translateY(100%)',
          pointerEvents: 'none',
        },
      },
    },
    right: {
      display: 'flex',
      alignItems: 'center',
      gap: t.space[3],
      flexShrink: 0,
      alignSelf: 'center',
    },
    searchWrapper: {
      position: 'relative',
      width: 'min(280px, 36vw)',
      minWidth: '180px',
      border: `${t.borderWidth.default} solid ${t.color.border.default}`,
      backgroundColor: t.color.background.surface,
      boxShadow: t.shadow.xs,
    },
    searchIcon: {
      position: 'absolute',
      left: `calc(${t.space[2]} + 2px)`,
      top: '50%',
      transform: 'translateY(-50%)',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      color: t.color.text.placeholder,
      pointerEvents: 'none',
      lineHeight: 0,
    },
    searchTrigger: {
      width: '100%',
      display: 'flex',
      alignItems: 'center',
      margin: 0,
      padding: `${t.space[2]} ${t.space[4]} ${t.space[2]} 32px`,
      fontSize: t.fontSize.sm,
      fontFamily: t.fontFamily.sans,
      textAlign: 'left',
      cursor: 'pointer',
      backgroundColor: 'transparent',
      border: 'none',
      color: t.color.text.secondary,
      outline: 'none',
      '&:hover': {
        backgroundColor: t.color.background.subtle,
        color: t.color.text.primary,
      },
      '&:focus-visible': {
        outline: `${t.borderWidth.thin} solid ${t.color.accent.default}`,
        outlineOffset: '-2px',
      },
    },
    searchKbd: {
      position: 'absolute',
      right: 0,
      top: 0,
      height: '100%',
      aspectRatio: 1,
      boxSizing: 'border-box',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: t.fontSize.xs,
      color: t.color.text.placeholder,
      backgroundColor: t.color.accent.subtle,
      paddingInline: t.space[2],
      fontFamily: t.fontFamily.sans,
      lineHeight: 1,
      pointerEvents: 'none',
    },
    githubIcon: {
      display: 'block',
      flexShrink: 0,
    },
    githubLink: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: t.space[2],
      padding: `${t.space[2]} ${t.space[4]}`,
      fontSize: t.fontSize.sm,
      fontWeight: t.fontWeight.bold,
      fontFamily: t.fontFamily.sans,
      textDecoration: 'none',
      color: t.color.text.primary,
      backgroundColor: t.color.background.surface,
      border: `${t.borderWidth.default} solid ${t.color.border.strong}`,
      boxShadow: t.shadow.sm,
      '&:hover': {
        backgroundColor: t.color.accent.default,
        color: t.color.text.onAccent,
      },
      '&:active': {
        boxShadow: 'none',
        transform: 'translate(2px, 2px)',
      },
    },
  },
  { layer: 'components' },
);
